apiVersion: v1
kind: Service
metadata:
  labels:
    app: inception
  name: inception
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: inception